new_todo:
  name: Create a To-Do
  description: Create a new To-Do
  target:
    device:
      integration: ms365_todo
    entity:
      integration: ms365_todo
      domain: todo
  fields:
    subject:
      name: Subject
      description: The subject of the To-Do
      example: Pick up the mail
      required: true
      selector:
        text:
    description:
      name: Description
      description: Description of the To-Do
      example: Walk to the post box and collect the mail
      selector:
        text:
    due:
      name: Due date
      description: When the To-Do is due by
      example: '"2025-01-01"'
      selector:
        date:
    reminder:
      name: Reminder date & time
      description: When a reminder is needed
      example: "2025-01-01T12:00:00+0000"
      selector:
        datetime:

update_todo:
  name: Update a To-Do
  description: Update a To-Do
  target:
    device:
      integration: ms365_todo
    entity:
      integration: ms365_todo
      domain: todo
  fields:
    todo_id:
      name: To-Do ID
      description: ID for the To-Do, can be found as an attribute on your todo
      example: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      required: true
      selector:
        text:
    subject:
      name: Subject
      description: The subject of the To-Do
      example: Pick up the mail
      selector:
        text:
    description:
      name: Description
      description: Description of the To-Do
      example: Walk to the post box and collect the mail
      selector:
        text:
    due:
      name: Due date
      description: When the To-Do is due by
      example: '"2025-01-01"'
      selector:
        date:
    reminder:
      name: reminder date & time
      description: When a reminder is needed
      example: "2025-01-01T12:00:00+0000"
      selector:
        datetime:

delete_todo:
  name: Delete a To-Do
  description: Delete a To-Do
  target:
    device:
      integration: ms365_todo
    entity:
      integration: ms365_todo
      domain: todo
  fields:
    todo_id:
      name: To-Do ID
      description: ID for the To-Do, can be found as an attribute on your todo
      example: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      required: true
      selector:
        text:

complete_todo:
  name: Complete a To-Do
  description: Complete a To-Do
  target:
    device:
      integration: ms365_todo
    entity:
      integration: ms365_todo
      domain: todo
  fields:
    todo_id:
      name: To-Do ID
      description: ID for the To-Do, can be found as an attribute on your todo
      example: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      required: true
      selector:
        text:
    completed:
      name: Completed
      description: Set whether To-Do is completed or not
      example: True
      required: true
      selector:
        boolean:

